name: Create New Manuscript Folder Structure

on:
  workflow_dispatch:
    inputs:
      publication_year:
        description: 'Enter 4-digit year of publication'
        required: true
      first_author_last_name:
        description: 'Enter last name of first author'
        required: true
      journal_name:
        description: 'Enter the journal name'
        required: true
      manuscript_title:
        description: 'Enter the manuscript title'
        required: true
      full_citation:
        description: 'Enter the full citation'
        required: true
      doi_link:
        description: 'Enter the DOI link'
        required: true        

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create new manuscript folder structure
        run: |
          # Capture inputs
          YEAR="${{ github.event.inputs.publication_year }}"
          AUTHOR="${{ github.event.inputs.first_author_last_name }}"
          JOURNAL="${{ github.event.inputs.journal_name }}"
          MANUSCRIPT="${{ github.event.inputs.manuscript_title }}"
          CITATION="${{ github.event.inputs.full_citation }}"
          DOILINK="${{ github.event.inputs.doi_link }}"          
          
          # Function to trim leading and trailing whitespace
          trim() {
            echo "$1" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
          }
          
          # Function to sanitize strings: trim, convert to lowercase, and replace non-alphanumeric characters with underscores
          sanitize() {
            local trimmed
            trimmed=$(trim "$1")
            echo "$trimmed" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g'
          }
          
          # Sanitize inputs
          S_YEAR=$(sanitize "$YEAR")
          S_AUTHOR=$(sanitize "$AUTHOR")
          S_JOURNAL=$(sanitize "$JOURNAL")
          
          # For the manuscript title: trim, then truncate to first 50 characters, then sanitize.
          TRIMMED_MANUSCRIPT=$(trim "$MANUSCRIPT")
          TRUNC_MANUSCRIPT="${TRIMMED_MANUSCRIPT:0:50}"
          S_MANUSCRIPT=$(sanitize "$TRUNC_MANUSCRIPT")
                    
          # Create folder name based on concatenation (delimited by underscores)          
          FOLDER_NAME="${S_YEAR}_${S_AUTHOR}_${S_JOURNAL}_${S_MANUSCRIPT}"                  
          
          # Create the folder structure and add placeholder files
          echo "Creating folder: $FOLDER_NAME"
          mkdir -p "$FOLDER_NAME/code" "$FOLDER_NAME/data"
          touch "$FOLDER_NAME/code/.gitkeep"
          touch "$FOLDER_NAME/data/.gitkeep"
      
          # Copy the template README from Template/README.md to the new manuscript folder
          cp Template/README.md "$FOLDER_NAME/README.md"

          # Prepend user input information to the README.md file
          {
            echo "ARTICLE: $CITATION"
            echo ""
            echo $DOILINK"
            echo ""
            echo "Publication year: $S_YEAR"
            echo ""
            echo "Author last name: $S_AUTHOR"
            echo ""
            echo "Journal name: $S_JOURNAL"
            echo ""
            echo "Manuscript title: $MANUSCRIPT"
            echo ""
            cat "$FOLDER_NAME/README.md"
          } > "$FOLDER_NAME/README.tmp" && mv "$FOLDER_NAME/README.tmp" "$FOLDER_NAME/README.md"
          
          
          # Configure Git (required for committing changes)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Stage and commit changes
          git add "$FOLDER_NAME"
          git commit -m "Add folder structure for manuscript: $FOLDER_NAME"
          git push
